namespace DataAccess.Helper;
public enum OrderBy
{
    Non = 0,
    ProductId = 1,
    Name = 2,
    BiggestPrice = 3,
    LowestPrice = 4,
    MaxQuantity = 5,
    MinQuantity = 6
}

/*
[product_id],
[product_code],
[product_fast_code],
[product_int_code],
[product_int_code1],
[product_int_code2],
[product_int_code3],
[product_int_code4],
[product_int_code5],
[product_int_code6],
[product_int_code7],
[product_int_code8],
[product_int_code9],
[product_int_code10],
[product_int_code11],
[product_int_code12],
[product_int_code13],
[product_int_code14],

[product_name_ar],
[product_name_en],
[product_scientific_name],
[product_drug],
[company_id],
[product_has_expire],
[site_id],
[product_buy_number],
[product_big_number],
[product_small_number],
[sell_price],
[product_disc1],
[product_disc2],
[tax_price],
[buy_price],
[deleted],
[active],
[product_unit1],
[product_unit2],
[product_unit3],
[product_unit1_2],
[product_unit1_3],
[group_id],
[pd_id],
[product_print_barcode],
[product_allow_disc],
[product_max_disc],
[insert_date],
[insert_uid],
[up_date],
[up_uid],
[notes],
[product_minus],
[product_made],
[product_sale_unit],
[product_unit1_sale],
[unit2_sell_price],
[unit3_sell_price],
[sell_clause],
[unit2_sell_price_clause],
[unit3_sell_price_clause],
[amount_zero],

[promo],
[promo_disc],
[promo_getonefree],
[no_print_name],
[no_allaw_return],
[offer_id],
[offer_type],
[stop_buy],
[product_points],
[not_allaw_r_sale],
[frozen],
[emp_max_disc],
[emp_insentive],
[GPC],
[EGS],
[tax_per]
*/