namespace DataAccess.Entities;
public class Employee
{
    public decimal? emp_id { get; set; }
    public string? emp_code { get; set; }
    public string? emp_name_ar { get; set; }
    public string? emp_name_en { get; set; }
    public string? emp_gender { get; set; }
    public decimal? job_id { get; set; }
    //public DateTime? birth_date { get; set; }
    //public DateTime? hire_date { get; set; }
    //public DateTime? work_date { get; set; }
    public string? mobile { get; set; }
    //public string? home_tel { get; set; }
    //public string? address { get; set; }
    //public string? card_id { get; set; }
    //public DateTime? card_date { get; set; }
    //public string? card_place { get; set; }
    public string? active { get; set; }
    //public decimal? max_disc_per { get; set; }
    //public decimal? max_disc_money { get; set; }
    //public string? show_buy { get; set; }
    //public string? show_cash_disk_history { get; set; }
    //public string? show_total_sales_report { get; set; }
    //public string? use_compu { get; set; }
    public string? username { get; set; }
    public string? pass { get; set; }
    //public DateTime? insert_date { get; set; }
    //public string? insert_uid { get; set; }
    //public string? update_uid { get; set; }
    //public DateTime? update_date { get; set; }
    public string? deleted { get; set; }
    //public string? salary_typ { get; set; }
    //public decimal? basic_salary { get; set; }
    //public decimal? more_salary { get; set; }
    //public string? emp_cust_max_money { get; set; }
    //public string? emp_add_product { get; set; }
    //public string? emp_edit_product { get; set; }
    //public string? emp_r_sale_date { get; set; }
    //public int? emp_r_sale_bill_num { get; set; }
    //public string? emp_add_cust { get; set; }
    //public string? emp_edit_cust { get; set; }
    //public string? emp_del_cust { get; set; }
    //public double? emp_commission1 { get; set; }
    //public double? emp_commission2 { get; set; }
    //public string? emp_edit_sell_price { get; set; }
    //public decimal? absence_money { get; set; }
    //public string? allaw_r_sale { get; set; }
    //public string? no_sales_credit { get; set; }
    //public string? emp_education { get; set; }
    //public string? emp_courses { get; set; }
    //public DateTime? contract_start_date { get; set; }
    //public DateTime? contract_end_date { get; set; }
    //public string? emp_insurance_id { get; set; }
    //public decimal? insurance_disc { get; set; }
    //public DateTime? insurance_date { get; set; }
    //public decimal? salary_tax { get; set; }
    //public string? emp_bank_id { get; set; }
    public string? emp_mail { get; set; }
    //public decimal? allowance1 { get; set; }
    //public decimal? allowance2 { get; set; }
    //public decimal? allowance3 { get; set; }
    //public decimal? allowance4 { get; set; }
    //public decimal? allowance5 { get; set; }
    //public decimal? allowance6 { get; set; }
    //public decimal? allowance7 { get; set; }
    //public decimal? allowance8 { get; set; }
    //public decimal? extra_day_money { get; set; }
    //public decimal? extra_hour_money { get; set; }
    //public decimal? extra_hour_holiday_money { get; set; }
    //public decimal? absence_day_money { get; set; }
    //public decimal? absence_day_off_money { get; set; }
    //public decimal? absence_hour_money { get; set; }
    //public decimal? tel_cut { get; set; }
    //public decimal? emp_box { get; set; }
    //public string? salary_id { get; set; }
    //public string? salary_cash_type { get; set; }
    //public byte[] emp_pic { get; set; }
    //public string? have_salary { get; set; }
    //public string? no_unsales { get; set; }
    //public decimal? cash_advance { get; set; }
    //public decimal? custody_money { get; set; }
    //public byte[] employee_data_file { get; set; }
    //public string? edit_salary { get; set; }
    //public string? edit_customer_disc { get; set; }
    //public int? emp_r_sale_days { get; set; }
    //public string? show_cash_total { get; set; }
    //public string? emp_del_order { get; set; }
    //public string? print_short_money { get; set; }
    //public string? show_customer_export { get; set; }
}
