namespace DataAccess.Entities;
public class Product
{
    public decimal? Product_id { get; set; }
    /*
    public string? product_code { get; set; }
    public string? product_fast_code { get; set; }
    public string? product_int_code { get; set; }
    public string? product_name_ar { get; set; }
    public string? product_name_en { get; set; }
    public string? product_scientific_name { get; set; }
    public int? product_drug { get; set; }
    public decimal? Company_id { get; set; }
    public string? product_has_expire { get; set; }
    public decimal? site_id { get; set; }
    public decimal? product_buy_number { get; set; }
    public decimal? product_big_number { get; set; }
    public decimal? product_small_number { get; set; }
    public decimal? sell_price { get; set; }
    public decimal? product_disc1 { get; set; }
    public decimal? product_disc2 { get; set; }
    public decimal? tax_price { get; set; }
    public decimal? buy_price { get; set; }
    public string? Deleted { get; set; }
    public string? Active { get; set; }
    public decimal? product_unit1 { get; set; }
    public decimal? product_unit2 { get; set; }
    public decimal? product_unit3 { get; set; }
    public decimal? product_unit1_2 { get; set; }
    public decimal? product_unit1_3 { get; set; }
    public decimal? group_id { get; set; }
    public decimal? pd_id { get; set; }
    public int product_print_barcode { get; set; }
    public int? product_allow_disc { get; set; }
    public double? product_max_disc { get; set; }
    public DateTime? Insert_date { get; set; }
    public string? Insert_uid { get; set; }
    public DateTime? up_date { get; set; }
    public string? up_uid { get; set; }
    public string? notes { get; set; }
    public string? product_minus { get; set; }
    public string? product_made { get; set; }
    public decimal? product_sale_unit { get; set; }
    public decimal? product_unit1_sale { get; set; }
    public decimal? unit2_sell_price { get; set; }
    public decimal? unit3_sell_price { get; set; }
    public decimal? sell_clause { get; set; }
    public decimal? unit2_sell_price_clause { get; set; }
    public decimal? unit3_sell_price_clause { get; set; }
    public string? amount_zero { get; set; }
    public string? product_int_code1 { get; set; }
    public string? product_int_code2 { get; set; }
    public string? product_int_code3 { get; set; }
    public string? product_int_code4 { get; set; }
    public string? product_int_code5 { get; set; }
    public string? product_int_code6 { get; set; }
    public string? product_int_code7 { get; set; }
    public string? product_int_code8 { get; set; }
    public string? product_int_code9 { get; set; }
    public string? product_int_code10 { get; set; }
    public string? product_int_code11 { get; set; }
    public string? product_int_code12 { get; set; }
    public string? product_int_code13 { get; set; }
    public string? product_int_code14 { get; set; }
    public string? promo { get; set; }
    public double? promo_disc { get; set; }
    public string? promo_getonefree { get; set; }
    public string? no_print_name { get; set; }
    public string? no_allaw_return { get; set; }
    public decimal? offer_id { get; set; }
    public decimal? offer_type { get; set; }
    public string? stop_buy { get; set; }
    public double? product_points { get; set; }
    public string? not_allaw_r_sale { get; set; }
    public string? frozen { get; set; }
    public double? emp_max_disc { get; set; }
    public double? emp_insentive { get; set; }
    public string? GPC { get; set; }
    public string? EGS { get; set; }
    public int? taxPer { get; set; }
    */
}